CREATE TABLE IF NOT EXISTS `Numbers` (
    `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `text` VARCHAR(100) NOT NULL UNIQUE,
    `year` INT NOT NULL UNIQUE,
    `type` VARCHAR(10) NOT NULL,

    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)